version: "2.1"

services:
  api:
    container_name: api_cnt
    build:
      context: .
      target: production
    ports:
      - 4000:4000
    networks:
      - mongo-network
    depends_on:
      - mongoDB

  mongoDB:
    image: mongo
    container_name: mongo-cnt
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./database/mongodb:/data/db
    networks:
      - mongo-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express-cnt
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongoDB
    depends_on:
      - mongoDB
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
